# Generated by Django 5.0.7 on 2026-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('rescuer', 'Rescuer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
